// import { TestBed } from '@angular/core/testing';

import { MessageService } from './message.service';

// This is an autogenerated integrated test
// describe('MessageService', () => {
//   beforeEach(() => TestBed.configureTestingModule({}));

//   it('should be created', () => {
//     const service: MessageService = TestBed.get(MessageService);
//     expect(service).toBeTruthy();
//   });
// });

describe('MessageService', () => {
  let service: MessageService;

  // set up
  beforeEach(() => {
    // arrange: each service is first intialized
    service = new MessageService();
  })

  it('should have no messages to start', () => {
    // assert: expectation before any method is actually used
    expect(service.messages.length).toBe(0);
  })

  it('should add a message when add is called', () => {
    // act: action (use method/function)
    service.add('message1');

    // assert: set expectation (add expected answer)
    expect(service.messages.length).toBe(1);
  })

  it('should remove all messages', () => {
    // arrange: define setup (in this case, make sure there are messages to clear)
    service.add('message2');

    // act: action (use method/function)
    service.clear()

    // assert: set expectation
    expect(service.messages.length).toBe(0);
  })
})
